# Generated by Django 4.0.3 on 2022-08-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=255)),
                ('max_humidity', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_ph', models.FloatField()),
                ('min_temp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Crop_name', models.CharField(max_length=255)),
                ('max_humidity', models.FloatField()),
                ('min_humidity', models.FloatField()),
                ('max_ph', models.FloatField()),
                ('max_temp', models.FloatField()),
                ('min_ph', models.FloatField()),
                ('min_temp', models.FloatField()),
                ('avg_humidity', models.FloatField()),
                ('avg_ph', models.FloatField()),
                ('avg_temp', models.FloatField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='avg_humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='avg_ph',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='avg_temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
