# Generated by Django 4.0.3 on 2022-08-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0003_locations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
