# Generated by Django 4.0.3 on 2022-08-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0005_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='summa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='MAP',
        ),
    ]
