# Generated by Django 4.0.3 on 2022-08-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0006_summa_delete_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegionName', models.CharField(choices=[('NA', 'North America'), ('AS', 'Asia')], max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='summa',
        ),
    ]
