# Generated by Django 4.0.3 on 2022-08-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0007_map_delete_summa'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='cities',
            field=models.CharField(choices=[('ON', 'Ontario'), ('AB', 'Alberta'), ('TO', 'Toronto'), ('QB', 'Quebec'), ('SN', 'Sinaloa'), ('BC', 'Baja California'), ('OZ', 'Orizabo'), ('CH', 'Chihuahua'), ('OA', 'Oaxaca'), ('AK', 'Arkansas'), ('WN', 'Washington'), ('GRG', 'Georgia'), ('TXS', 'Texas'), ('IW', 'Iowa'), ('KR', 'Krasnodar'), ('RT', 'Rostov'), ('ST', 'Stavropol'), ('SB', 'Siberia'), ('FZ', 'Faizabad'), ('AM', 'Amritsar'), ('KTK', 'Kolkata'), ('AMD', 'Ahmedabad'), ('CHW', 'Chhindwara'), ('GZ', 'Guizhou'), ('GDG', 'Guangdong'), ('XNG', 'Xinjiang'), ('UQI', 'Urumqi')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='country',
            field=models.CharField(choices=[('CA', 'Canada'), ('MX', 'Mexico'), ('US', 'United States'), ('RU', 'Russia'), ('IND', 'India'), ('CH', 'China')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
