# Generated by Django 4.0.3 on 2022-08-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_map_cities_map_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='avg_humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='avg_ph',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='avg_temp',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
