# Generated by Django 4.0.3 on 2022-08-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_location_avg_humidity_location_avg_ph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='price',
        ),
    ]
